#ifndef LA_NUMERIC_METHODS_SOLVER_CONSTS
#define LA_NUMERIC_METHODS_SOLVER_CONSTS

#include "../liblogicanalyzer.h"
#include <stdlib.h>

#define LA_SOLVER_RK5_STAGES 7
extern const double LA_SOLVER_RK5_A_DATA[LA_SOLVER_RK5_STAGES * LA_SOLVER_RK5_STAGES];
extern const double LA_SOLVER_RK5_B_DATA[LA_SOLVER_RK5_STAGES];
extern const double LA_SOLVER_RK5_C_DATA[LA_SOLVER_RK5_STAGES];

#define LA_SOLVER_RK6_STAGES 7
extern const double LA_SOLVER_RK6_A_DATA[LA_SOLVER_RK6_STAGES * LA_SOLVER_RK6_STAGES];
extern const double LA_SOLVER_RK6_B_DATA[LA_SOLVER_RK6_STAGES];
extern const double LA_SOLVER_RK6_C_DATA[LA_SOLVER_RK6_STAGES];

#define LA_SOLVER_RK8_STAGES 11
extern const double LA_SOLVER_RK8_A_DATA[LA_SOLVER_RK8_STAGES * LA_SOLVER_RK8_STAGES];
extern const double LA_SOLVER_RK8_B_DATA[LA_SOLVER_RK8_STAGES];
extern const double LA_SOLVER_RK8_C_DATA[LA_SOLVER_RK8_STAGES];

#define LA_SOLVER_RKF45_STAGES 6
extern const double LA_SOLVER_RKF45_A_DATA[LA_SOLVER_RKF45_STAGES * LA_SOLVER_RKF45_STAGES];
extern const double LA_SOLVER_RKF45_B_DATA[LA_SOLVER_RKF45_STAGES];
extern const double LA_SOLVER_RKF45_C_DATA[LA_SOLVER_RKF45_STAGES*2];

#define LA_SOLVER_DOP45_STAGES 7
extern const double LA_SOLVER_DOP45_A_DATA[LA_SOLVER_DOP45_STAGES * LA_SOLVER_DOP45_STAGES];
extern const double LA_SOLVER_DOP45_B_DATA[LA_SOLVER_DOP45_STAGES];
extern const double LA_SOLVER_DOP45_C_DATA[LA_SOLVER_DOP45_STAGES*2];

#define LA_SOLVER_BS23_STAGES 4
extern const double LA_SOLVER_BS23_A_DATA[LA_SOLVER_BS23_STAGES * LA_SOLVER_BS23_STAGES];
extern const double LA_SOLVER_BS23_B_DATA[LA_SOLVER_BS23_STAGES];
extern const double LA_SOLVER_BS23_C_DATA[LA_SOLVER_BS23_STAGES*2];

#define LA_SOLVER_RKCK45_STAGES 6
extern const double LA_SOLVER_RKCK45_A_DATA[LA_SOLVER_RKCK45_STAGES * LA_SOLVER_RKCK45_STAGES];
extern const double LA_SOLVER_RKCK45_B_DATA[LA_SOLVER_RKCK45_STAGES];
extern const double LA_SOLVER_RKCK45_C_DATA[LA_SOLVER_RKCK45_STAGES*2];

#define LA_SOLVER_ODE12_STAGES 2
extern const double LA_SOLVER_ODE12_A_DATA[LA_SOLVER_ODE12_STAGES * LA_SOLVER_ODE12_STAGES];
extern const double LA_SOLVER_ODE12_B_DATA[LA_SOLVER_ODE12_STAGES];
extern const double LA_SOLVER_ODE12_C_DATA[LA_SOLVER_ODE12_STAGES*2];

#define LA_SOLVER_RKF78_STAGES 13
extern const double LA_SOLVER_RKF78_A_DATA[LA_SOLVER_RKF78_STAGES * LA_SOLVER_RKF78_STAGES];
extern const double LA_SOLVER_RKF78_B_DATA[LA_SOLVER_RKF78_STAGES];
extern const double LA_SOLVER_RKF78_C_DATA[LA_SOLVER_RKF78_STAGES*2];

#define LA_SOLVER_GL4_STAGES 2
extern const double LA_SOLVER_GL4_A_DATA[LA_SOLVER_GL4_STAGES * LA_SOLVER_GL4_STAGES];
extern const double LA_SOLVER_GL4_B_DATA[LA_SOLVER_GL4_STAGES];
extern const double LA_SOLVER_GL4_C_DATA[LA_SOLVER_GL4_STAGES];

#define LA_SOLVER_GL6_STAGES 3
extern const double LA_SOLVER_GL6_A_DATA[LA_SOLVER_GL6_STAGES * LA_SOLVER_GL6_STAGES];
extern const double LA_SOLVER_GL6_B_DATA[LA_SOLVER_GL6_STAGES];
extern const double LA_SOLVER_GL6_C_DATA[LA_SOLVER_GL6_STAGES];

#define LA_SOLVER_R1A3_STAGES 2
extern const double LA_SOLVER_R1A3_A_DATA[LA_SOLVER_R1A3_STAGES * LA_SOLVER_R1A3_STAGES];
extern const double LA_SOLVER_R1A3_B_DATA[LA_SOLVER_R1A3_STAGES];
extern const double LA_SOLVER_R1A3_C_DATA[LA_SOLVER_R1A3_STAGES];

#define LA_SOLVER_R1A5_STAGES 3
extern const double LA_SOLVER_R1A5_A_DATA[LA_SOLVER_R1A5_STAGES * LA_SOLVER_R1A5_STAGES];
extern const double LA_SOLVER_R1A5_B_DATA[LA_SOLVER_R1A5_STAGES];
extern const double LA_SOLVER_R1A5_C_DATA[LA_SOLVER_R1A5_STAGES];

#define LA_SOLVER_R2A3_STAGES 2
extern const double LA_SOLVER_R2A3_A_DATA[LA_SOLVER_R2A3_STAGES * LA_SOLVER_R2A3_STAGES];
extern const double LA_SOLVER_R2A3_B_DATA[LA_SOLVER_R2A3_STAGES];
extern const double LA_SOLVER_R2A3_C_DATA[LA_SOLVER_R2A3_STAGES];

#define LA_SOLVER_R2A5_STAGES 3
extern const double LA_SOLVER_R2A5_A_DATA[LA_SOLVER_R2A5_STAGES * LA_SOLVER_R2A5_STAGES];
extern const double LA_SOLVER_R2A5_B_DATA[LA_SOLVER_R2A5_STAGES];
extern const double LA_SOLVER_R2A5_C_DATA[LA_SOLVER_R2A5_STAGES];

#define LA_SOLVER_L3A2_STAGES 2
extern const double LA_SOLVER_L3A2_A_DATA[LA_SOLVER_L3A2_STAGES * LA_SOLVER_L3A2_STAGES];
extern const double LA_SOLVER_L3A2_B_DATA[LA_SOLVER_L3A2_STAGES];
extern const double LA_SOLVER_L3A2_C_DATA[LA_SOLVER_L3A2_STAGES];

#define LA_SOLVER_L3A4_STAGES 3
extern const double LA_SOLVER_L3A4_A_DATA[LA_SOLVER_L3A4_STAGES * LA_SOLVER_L3A4_STAGES];
extern const double LA_SOLVER_L3A4_B_DATA[LA_SOLVER_L3A4_STAGES];
extern const double LA_SOLVER_L3A4_C_DATA[LA_SOLVER_L3A4_STAGES];

#define LA_SOLVER_L3A6_STAGES 4
extern const double LA_SOLVER_L3A6_A_DATA[LA_SOLVER_L3A6_STAGES * LA_SOLVER_L3A6_STAGES];
extern const double LA_SOLVER_L3A6_B_DATA[LA_SOLVER_L3A6_STAGES];
extern const double LA_SOLVER_L3A6_C_DATA[LA_SOLVER_L3A6_STAGES];

#define LA_SOLVER_L3A8_STAGES 5
extern const double LA_SOLVER_L3A8_A_DATA[LA_SOLVER_L3A8_STAGES * LA_SOLVER_L3A8_STAGES];
extern const double LA_SOLVER_L3A8_B_DATA[LA_SOLVER_L3A8_STAGES];
extern const double LA_SOLVER_L3A8_C_DATA[LA_SOLVER_L3A8_STAGES];

#define LA_SOLVER_L3B2_STAGES 2
extern const double LA_SOLVER_L3B2_A_DATA[LA_SOLVER_L3B2_STAGES * LA_SOLVER_L3B2_STAGES];
extern const double LA_SOLVER_L3B2_B_DATA[LA_SOLVER_L3B2_STAGES];
extern const double LA_SOLVER_L3B2_C_DATA[LA_SOLVER_L3B2_STAGES];

#define LA_SOLVER_L3B4_STAGES 3
extern const double LA_SOLVER_L3B4_A_DATA[LA_SOLVER_L3B4_STAGES * LA_SOLVER_L3B4_STAGES];
extern const double LA_SOLVER_L3B4_B_DATA[LA_SOLVER_L3B4_STAGES];
extern const double LA_SOLVER_L3B4_C_DATA[LA_SOLVER_L3B4_STAGES];

#define LA_SOLVER_L3B6_STAGES 4
extern const double LA_SOLVER_L3B6_A_DATA[LA_SOLVER_L3B6_STAGES * LA_SOLVER_L3B6_STAGES];
extern const double LA_SOLVER_L3B6_B_DATA[LA_SOLVER_L3B6_STAGES];
extern const double LA_SOLVER_L3B6_C_DATA[LA_SOLVER_L3B6_STAGES];

#define LA_SOLVER_L3B8_STAGES 5
extern const double LA_SOLVER_L3B8_A_DATA[LA_SOLVER_L3B8_STAGES * LA_SOLVER_L3B8_STAGES];
extern const double LA_SOLVER_L3B8_B_DATA[LA_SOLVER_L3B8_STAGES];
extern const double LA_SOLVER_L3B8_C_DATA[LA_SOLVER_L3B8_STAGES];

#define LA_SOLVER_L3C2_STAGES 2
extern const double LA_SOLVER_L3C2_A_DATA[LA_SOLVER_L3C2_STAGES * LA_SOLVER_L3C2_STAGES];
extern const double LA_SOLVER_L3C2_B_DATA[LA_SOLVER_L3C2_STAGES];
extern const double LA_SOLVER_L3C2_C_DATA[LA_SOLVER_L3C2_STAGES];

#define LA_SOLVER_L3C4_STAGES 3
extern const double LA_SOLVER_L3C4_A_DATA[LA_SOLVER_L3C4_STAGES * LA_SOLVER_L3C4_STAGES];
extern const double LA_SOLVER_L3C4_B_DATA[LA_SOLVER_L3C4_STAGES];
extern const double LA_SOLVER_L3C4_C_DATA[LA_SOLVER_L3C4_STAGES];

#define LA_SOLVER_L3C6_STAGES 4
extern const double LA_SOLVER_L3C6_A_DATA[LA_SOLVER_L3C6_STAGES * LA_SOLVER_L3C6_STAGES];
extern const double LA_SOLVER_L3C6_B_DATA[LA_SOLVER_L3C6_STAGES];
extern const double LA_SOLVER_L3C6_C_DATA[LA_SOLVER_L3C6_STAGES];

#define LA_SOLVER_L3C8_STAGES 5
extern const double LA_SOLVER_L3C8_A_DATA[LA_SOLVER_L3C8_STAGES * LA_SOLVER_L3C8_STAGES];
extern const double LA_SOLVER_L3C8_B_DATA[LA_SOLVER_L3C8_STAGES];
extern const double LA_SOLVER_L3C8_C_DATA[LA_SOLVER_L3C8_STAGES];


#endif //LA_NUMERIC_METHODS_SOLVER_CONSTS
